"""fix line_users user_id length

Revision ID: 5fa385e017ac
Revises: 9258942c773a
Create Date: 2025-06-03 22:51:38.715865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa385e017ac'
down_revision: Union[str, None] = '9258942c773a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_uid', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'line_uid')
    )
    op.create_index(op.f('ix_line_users_id'), 'line_users', ['id'], unique=False)
    op.create_index(op.f('ix_line_users_line_uid'), 'line_users', ['line_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_users_line_uid'), table_name='line_users')
    op.drop_index(op.f('ix_line_users_id'), table_name='line_users')
    op.drop_table('line_users')
    # ### end Alembic commands ###
