"""init

Revision ID: 9258942c773a
Revises: 
Create Date: 2025-06-03 22:46:21.306863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9258942c773a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_index(op.f('ix_line_users_id'), 'line_users', ['id'], unique=False)
    op.create_index(op.f('ix_line_users_user_id'), 'line_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_users_user_id'), table_name='line_users')
    op.drop_index(op.f('ix_line_users_id'), table_name='line_users')
    op.drop_table('line_users')
    # ### end Alembic commands ###
