"""add tax columns

Revision ID: a71a7103d155
Revises: 
Create Date: 2025-06-02 21:02:43.289696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71a7103d155'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total_excluding_tax', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('total_tax', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_tax')
    op.drop_column('transactions', 'total_excluding_tax')
    # ### end Alembic commands ###
